### working of numpy dataset

In [1]:
import numpy as np 

In [2]:
np.full(5,5)

array([5, 5, 5, 5, 5])

In [3]:
np.full(3,5)

array([5, 5, 5])

In [4]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

#### random elements of float values B/w Range 0 to 1

In [8]:
np.random.random((2,3))

array([[0.40322468, 0.14914137, 0.61872191],
       [0.79527995, 0.51929125, 0.15345428]])

#### random elements of int values B/w Range 1 to n

In [9]:
np.random.randint((2,3))

array([0, 2], dtype=int32)

In [10]:
np.random.randint((1,10))

array([0, 5], dtype=int32)

### Random number with single dimension

In [14]:
np.random.randint(1,10,(5))

array([9, 8, 8, 7, 5], dtype=int32)

### Random int with single dimension

In [16]:
np.random.randint(1,10,5)

array([4, 7, 7, 9, 4], dtype=int32)

### Random int with Two dimension

In [15]:
np.random.randint(1,10,(2,5))

array([[7, 5, 4, 3, 2],
       [9, 2, 2, 3, 7]], dtype=int32)

### Random int with Three dimension

In [17]:
np.random.randint(1,10,(2,5,3))

array([[[4, 6, 7],
        [9, 3, 5],
        [8, 1, 2],
        [9, 1, 3],
        [9, 9, 5]],

       [[6, 3, 2],
        [9, 5, 5],
        [3, 1, 5],
        [9, 9, 7],
        [9, 4, 4]]], dtype=int32)

### Like there range in python similary in numpy we have arange array

In [18]:
B = np.arange(1,10)

In [19]:
print(B)

[1 2 3 4 5 6 7 8 9]


In [20]:
B = np.arange(1,10,2)

In [21]:
print(B)

[1 3 5 7 9]


In [25]:
B = np.arange(1,10,2).reshape((5,1))

In [26]:
print(B)

[[1]
 [3]
 [5]
 [7]
 [9]]


In [27]:
x = np.arange(16.0).reshape(4, 4)
print(x)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [28]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Important Points of reshape is  (Trick shape (rxc) = no of elements) then only it can transformed

In [29]:
a = np.arange(6)

In [30]:
print(a)

[0 1 2 3 4 5]


In [31]:
print('size of a=',a.size)

size of a= 6


In [32]:
print(a.reshape(1,6))
print(a.reshape(6,1))
print(a.reshape(2,3))
print(a.reshape(3,2))

[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [36]:
print(a)

[0 1 2 3 4 5]


In [34]:
print(a.reshape(2,3,order='C')) #C style : row wise preference

[[0 1 2]
 [3 4 5]]


In [35]:
print(a.reshape(2,3,order='F'))  #Fortran style : column wise preference

[[0 2 4]
 [1 3 5]]


####  Dimension Transformations (reshaping) 1D -> 2D -> 3D

In [37]:
n = np.arange(8) #8 elements

In [38]:
print(n)

[0 1 2 3 4 5 6 7]


### Finding the Possible factors for reshaping

In [47]:
def getFactors(l):
    x = []
    y = []
    size =  l.size
    for i in range(1,l.size+1):
        if size%i == 0:
            q = size//i
            x.append(q)
            y.append(i)
    return list(zip(x,y))
    
        
getFactors(n)     

[(8, 1), (4, 2), (2, 4), (1, 8)]

### How to dynamically calcualate the possible shape

In [48]:
def reshapes_values(l):
    x = []
    y = []
    size =  l.size
    for i in range(1,l.size+1):
        if size%i == 0:
            q = size//i
            x.append(q)
            y.append(i)
    return list(zip(x,y))
    
        
reshapes_values(n)     

[(8, 1), (4, 2), (2, 4), (1, 8)]

#### Once we are done with possible factors we try to reshape the array

In [49]:
print(n.reshape(1,8))

[[0 1 2 3 4 5 6 7]]


In [50]:
print(n.reshape(2,4))

[[0 1 2 3]
 [4 5 6 7]]


In [51]:
print(n.reshape(4,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### using total size or size

In [57]:
print(n.reshape(8,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


### Auto-reshape (-1) automatically takes nsize

In [53]:
print(n.reshape(-1,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


### case 1- Converting to 3d = multiplication = size of elements

In [54]:
print(n.reshape(2,2,2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### case 2- Converting to 3d = multiplication = size of elements

In [55]:
print(n.reshape(4,1,2))

[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]]
