### Universal Function in Numpy 

There are two main operation in numpy 

 **Vectorization Technique**
 
 - scalar operation : element wise operation
 - vector operation : matrix wise operation - vector operation

In [3]:
import numpy as np

#### Scalar technique : scalar value = 5

In [4]:

A = np.array([1,2,3,4])
B = A+5 
print(B)

[6 7 8 9]


#### Vector technique : vector value (n dimensional) = [1,2,3]

In [5]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = [1,2,3]
print(matrix*vector)

[[ 1  4  9]
 [ 4 10 18]]


In [6]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([1,2,3])
print(matrix*vector)

[[ 1  4  9]
 [ 4 10 18]]


#### Calculating the Sum and mean

In [9]:
a = np.array([1,2,3,4,5,6])
print('sum =',np.sum(a))
print('mean=',np.mean(a))

sum = 21
mean= 3.5


In [10]:
print('avg=',np.sum(a)/a.size)

avg= 3.5


#### How to calculate standard deviation (std) and variance (var)

In [11]:
print('Standard Deviation=',np.std(a))
print('Variance=',np.var(a))

Standard Deviation= 1.707825127659933
Variance= 2.9166666666666665


In [12]:
print('Standard Deviation (precision for 2 values)=',round(np.std(a),2))
print('Variance (precision for 2 values) =',round(np.var(a)))

Standard Deviation (precision for 2 values)= 1.71
Variance (precision for 2 values) = 3


#### using math module with numpy with scalar operation of permuation and combination

In [15]:
import math as m 

In [16]:
A =  np.arange(1,10)
print(A)

[1 2 3 4 5 6 7 8 9]


#### scalar operation with permuations 

In [17]:
B = A + m.perm(A.size,2)
print(B)

[73 74 75 76 77 78 79 80 81]


#### scalar operation with combinations

In [18]:
B = A + m.comb(A.size,2)
print(B)

[37 38 39 40 41 42 43 44 45]


#### min and max 

In [22]:
print('minimum of the a =',np.min(a))
print('max of the a =',np.max(a))

minimum of the a = 1
max of the a = 6


#### power and remainder

In [24]:
print('power of a =',np.power(a,2))
print('Remainder of the a =',np.mod(a,2))

power of a = [ 1  4  9 16 25 36]
Remainder of the a = [1 0 1 0 1 0]


#### trignometric and logarithmic

In [29]:
import math as m

In [31]:
print('sin =',np.sin(a))

sin 30= [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [33]:
deg = m.pi/6
print('degree',deg)


degree 0.5235987755982988


In [34]:
print(f'sin value of {deg}',np.sin(a)*deg)

sin value of 0.5235987755982988 [ 0.44059318  0.47610702  0.07389026 -0.39626086 -0.50209158 -0.14630161]


In [37]:
print('logarithm of e=',np.log(a))
print('logarithm of base 2=',np.log2(a))
print('logarithm of base 10=',np.log10(a))

logarithm of e= [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
logarithm of base 2= [0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
logarithm of base 10= [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]
