### using numpy for Matrix and determinants  : Linear Algebra ➡️ np.linalg()

In [1]:
import numpy as np

In [2]:
matA = np.array([1,2,3])
matB = np.array([4,5,6])

### Addition and subtraction, with multiplication and division

In [3]:
print('Addition :',np.add(matA,matB))

Addition : [5 7 9]


In [4]:
print('Subract :',np.subtract(matA,matB))

Subract : [-3 -3 -3]


In [5]:
print('Mulitiply :',np.multiply(matA,matB))

Mulitiply : [ 4 10 18]


In [6]:
print('Divide :',np.divide(matA,matB))

Divide : [0.25 0.4  0.5 ]


#### Matrix Algebra  for 2d Addition,subtraction,multiply and division 

In [8]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])



#### Printing of the Matrix A and B

In [10]:
print('A =\n',A)
print('B = \n',B)

A =
 [[1 2]
 [3 4]]
B = 
 [[5 6]
 [7 8]]


#### Order of the Matrix 

In [11]:
print('shape of A=\n',A.shape)
print('shape of B=\n',B.shape)

shape of A=
 (2, 2)
shape of B=
 (2, 2)


In [13]:
print('type:',type(A.shape))

type: <class 'tuple'>


**Note : the numpy matrix does not support any pre-defined method to check if the matrix is square or not hence we need to explicitly check row = column**

**Hint : A.shape => tuple => (rows, columns) position of rows : 0th position of the column : 1th
index of 0th == index of 1st => matrix is square**

#### Functions to check if the matrix is square or not

In [15]:
def is_square_matrix(matrix):
        row = matrix.shape[0]
        cols = matrix.shape[1]
        if row == cols:
            return True
        else:
            return False

In [19]:
C = np.array([
    [1,2,3],
    [4,5,6]
])
print(C.shape)

(2, 3)


#### Checking the Matrix if it is square or not

In [20]:
print('is C square Matrix =\n',is_square_matrix(C))

is C square Matrix =
 False


In [16]:
print('is A square Matrix =\n',is_square_matrix(A))

is A square Matrix =
 True


In [21]:
print('is B square Matrix =\n',is_square_matrix(B))

is B square Matrix =
 True


**Note : in Rectangular Matrix its order can be changed, hence shape and reshape will effect but in case of the square matrix
reshaping will not change the order but definetly position of the element may change significantly.**

#### Matrix Operations

In [27]:
print('Addition :\n',np.add(A,B))

Addition :
 [[ 6  8]
 [10 12]]


In [28]:
print('Subract :\n',np.subtract(A,B))

Subract :
 [[-4 -4]
 [-4 -4]]


In [29]:
print('Mulitiply :\n',np.multiply(A,B))

Mulitiply :
 [[ 5 12]
 [21 32]]


In [30]:
print('Divide :\n',np.divide(A,B))

Divide :
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


#### Operation with different Shape

In [31]:
print('Divide A with C :\n',np.divide(A,C))

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

#### Vector product 

In [33]:
print('Vector Product A with B :\n',np.dot(A,B))

Vector Product A with B :
 [[19 22]
 [43 50]]


### Transpose of the Matrix 

In [37]:
print('Transpose : \n ',np.transpose(A))

Transpose : 
  [[1 3]
 [2 4]]


In [39]:
print('Transpose : \n ',A.T)

Transpose : 
  [[1 3]
 [2 4]]


### Inverse of the Matrix 

In [40]:
print('Inverse of A or A^-1 or Arc(A) =\n',np.linalg.inv(A)) 

Inverse of A or A^-1 or Arc(A) =
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Determinant of the Matrix

In [42]:
print('Determinant |A| =\n',np.linalg.det(A)) 

Determinant |A| =
 -2.0000000000000004


In [47]:
#### Eigen value and Eigen Vectors 
eigen_value,eigen_vector = np.linalg.eig(A)

In [49]:
print(f'eigen_value = {eigen_value},\n eigen_vector ={eigen_vector}')

eigen_value = [-0.37228132  5.37228132],
 eigen_vector =[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
