#### what is numpy 

**numpy stands for numerical python, it is used for several mathematical calculations. involving different matrix operations.
the task performed using list will be easily resolved using numpy**

#### List Vs Numpy

In [3]:
lst = [i for i in range(100000)]

In [5]:
from time import process_time

In [6]:
start_time = process_time()
new_lst = [x**2 for x in lst]
end_time = process_time()
print(f'Total Time taken = {round(end_time-start_time,2)} seconds')

Total Time taken = 0.03 seconds


In [7]:
import numpy as np

In [8]:
np_array =  np.array([i for i in range(100000)])

In [9]:
start_time = process_time()
new_np_array = np_array**2
end_time = process_time()
print(f'Total Time taken = {round(end_time-start_time,2)} seconds')

Total Time taken = 0.0 seconds


In [10]:
print(new_np_array)

[         0          1          4 ... 9999400009 9999600004 9999800001]


In [11]:
# creating a basic numpy array 
basic_array =  np.array([1,2,3])
print('Basic Array',basic_array)

Basic Array [1 2 3]


In [12]:
l = [1,2,3]
print('basic list',l)

basic list [1, 2, 3]


In [13]:
l = [1,2,3]
print('basic list',l)
print('Type:',type(basic_array))
print('Data Type:',basic_array.dtype)

basic list [1, 2, 3]
Type: <class 'numpy.ndarray'>
Data Type: int64


In [16]:
A = np.array([
    [1,2,3],
    [2,3,4],
    [5,6,7]
])

In [17]:
print(A)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [18]:
print('Order or shape',A.shape)

Order or shape (3, 3)


In [19]:
B = np.array([1,2,3])
print(f' value of B {B} and shape of B = {B.shape}')

 value of B [1 2 3] and shape of B = (3,)


In [21]:
zeros_array = np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
ranged_array = np.arange(0,10,2)

In [26]:
print(ranged_array)

[0 2 4 6 8]


In [27]:
#Finding the equidistant points between 2 Range
linspace_array = np.linspace(10,30,5)
print(linspace_array)

[10. 15. 20. 25. 30.]


In [28]:
#Finding the equidistant points between 2 Range
linspace_array = np.linspace(10,30,6)
print(linspace_array)

[10. 14. 18. 22. 26. 30.]


### what is Identity Matrix 

In [31]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Array Attributes and Properties.

In [33]:
array =  np.array([[1,2,3],[4,5,6]])

In [34]:
print('shape',array.shape)
print('Number of dimension',array.ndim)
print('Total Element',array.size)
print('item size',array.itemsize)
print('Total Bytes:',array.nbytes)
print('Tranposed \n',array.T)

shape (2, 3)
Number of dimension 2
Total Element 6
item size 8
Total Bytes: 48
Tranposed 
 [[1 4]
 [2 5]
 [3 6]]
